[project]
name = "greeting-api"
version = "1.0.0"
description = "API de Saludo - Proyecto Semana 01 (SoluciÃ³n)"
readme = "README.md"
requires-python = ">=3.14"

dependencies = [
    "fastapi[standard]>=0.128.0",
]
